# Generated by Django 4.1 on 2022-09-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(choices=[('Vintage White', 'Vintage White'), ('Fire Red', 'Fire Red')], default='Vintage White', max_length=30),
        ),
        migrations.AlterField(
            model_name='gameroute',
            name='gameId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='pnrDB.game'),
        ),
    ]
