# Generated by Django 4.1 on 2022-09-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0002_alter_game_name_alter_gameroute_gameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move', to='pnrDB.move')),
                ('pokemonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pnrDB.pokemon')),
            ],
        ),
    ]
