# Generated by Django 4.1 on 2022-09-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0003_pokemonmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='name',
            field=models.CharField(default='move', max_length=100),
        ),
    ]
