# Generated by Django 4.1 on 2022-09-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0004_pokemonmove_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonmove',
            name='name',
        ),
    ]
