# Generated by Django 4.1 on 2022-09-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0006_pokemonmove_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmove',
            name='name',
            field=models.CharField(default='TrainerName PokemonName MoveName', max_length=1000),
        ),
    ]
