# Generated by Django 4.1 on 2022-09-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0007_alter_pokemonmove_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='trainerId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='pnrDB.trainer'),
        ),
    ]
