# Generated by Django 4.1 on 2022-09-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0008_pokemonmove_trainerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='routeId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='route', to='pnrDB.gameroute'),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='name',
            field=models.CharField(default='TrainerName PokemonName MoveName RouteName', max_length=1000),
        ),
    ]
