# Generated by Django 4.1 on 2022-09-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0009_pokemonmove_routeid_alter_pokemonmove_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonOnRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('pokemonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routePokemon', to='pnrDB.pokemon')),
                ('routeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemonRoute', to='pnrDB.gameroute')),
            ],
        ),
    ]
