# Generated by Django 4.1 on 2022-09-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0010_pokemononroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('pokemoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxPokemomn', to='pnrDB.pokemon')),
                ('runId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxRun', to='pnrDB.run')),
            ],
        ),
    ]
