# Generated by Django 4.1 on 2022-09-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0012_alter_game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxpokemon',
            old_name='pokemoId',
            new_name='pokemonId',
        ),
    ]
