# Generated by Django 4.1 on 2022-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0014_remove_game_runid_run_gameid_alter_run_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
