# Generated by Django 4.1 on 2022-09-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0017_user_email_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='eMail',
        ),
    ]
