# Generated by Django 4.1 on 2022-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnrDB', '0018_rename_email_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eMail',
            field=models.CharField(default='1@gmail.com', max_length=100),
        ),
    ]
